# Generated by Django 3.1.1 on 2021-06-21 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ekabis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='İsim')),
                ('sorumlu', models.CharField(blank=True, max_length=120, null=True, verbose_name='Sorumlu')),
                ('isFormal', models.BooleanField(choices=[(True, 'Bireysel'), (False, 'Kurumsal')], default=False)),
                ('degree', models.CharField(blank=True, max_length=120, null=True, verbose_name='Unvan')),
                ('taxOffice', models.CharField(blank=True, max_length=120, null=True, verbose_name='Vergi Dairesi ')),
                ('taxnumber', models.CharField(blank=True, max_length=120, null=True, verbose_name='Vergi Numarasi  ')),
                ('mail', models.CharField(blank=True, max_length=120, null=True, verbose_name='mail')),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('operationDate', models.DateTimeField(auto_now=True)),
                ('kobilid', models.IntegerField(blank=True, default=1, null=True)),
                ('JopDescription', models.ManyToManyField(to='ekabis.CategoryItem')),
                ('communication', models.OneToOneField(db_column='communication', on_delete=django.db.models.deletion.CASCADE, to='ekabis.communication')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
    ]
