# Generated by Django 3.1.1 on 2021-06-21 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ekabis', '0002_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='JopDescription',
        ),
    ]
