# Generated by Django 3.2.9 on 2021-11-15 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekabis', '0002_auto_20211101_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='is_parent',
            field=models.BooleanField(),
        ),
    ]
