# Generated by Django 3.1.1 on 2021-06-21 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekabis', '0003_remove_company_jopdescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='JopDescription',
            field=models.ManyToManyField(to='ekabis.CategoryItem'),
        ),
    ]
